version: "3.9"
services:
  pg:
    image: pgvector/pgvector:pg16   # образ Postgres c pgvector внутри
    container_name: vkr_pg
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vkr
    ports: ["5432:5432"]
    volumes:
      - ./sql:/docker-entrypoint-initdb.d  # применит 001_init.sql
